config/routes.rb
Rails.application.routes.draw do

root 'instruments#index'

resources :instruments

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  validates :name, :group, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def index
    @instruments = Instrument.all
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    if @instrument.save
      redirect_to instruments_path
    else
      redirect_to insruments_path, notice: "Instrument not created"
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

  def edit
    @instrument = Instrument.find(params[:id])
  end

  def update
    @instrument = Instrument.find(params[:id])
    @instrument.update(instrument_params)
    if @instrument.save
      redirect_to instrument_path
    else
      redirect_to edit_instrument_path, notice: "Instrument not updated"
    end
  end

  def delete
    @instrument = Instrument.find(params[:id])
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    if @instrument.destroy
      redirect_to instruments_path
    end
  end

  private
  def instrument_params
    params.require(:instrument).permit(:name, :group, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instruments/_form.html.erb
<%= form_for @instrument do |f| %>
  <div>
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :group %>:
    <%= f.text_field :group %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <%= f.submit %>

<% end %>

app/views/instruments/edit.html.erb
Edit page for <%= @instrument.name %>

<%= render partial: 'form' %>

app/views/instruments/index.html.erb
<h1>Instruments</h1>

<% @instruments.each do |instrument| %>
  <%= link_to instrument.name, instrument %>
  <%= button_to 'delete', instrument, method: :delete %>
  <br>
<% end %>

<%= link_to "Add an instrument", new_instrument_path %>

app/views/instruments/new.html.erb
<h1>Make an instrument</h1>

<%= render partial: 'form' %>

app/views/instruments/show.html.erb
<h1>an Instrument</h1>

<p>
<%= @instrument.name %>
</p>

<p>
  <%= @instrument.group %>
</p>

<p>
  <%= @instrument.price %>
</p>

<%= link_to "Edit this instrument", edit_instrument_path(@instrument.id) %>
<%= link_to "Back to Instrument list", instruments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicalInstruments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>